custom user model created
anarbyrm/cargo-api pull request #3
Opened 2023-01-21 17:52 UTC by anarbyrm

2023-01-23 18:19 UTC, anarbyrm commented
conflict resolved

2023-01-23 20:17 UTC, anarbyrm commented
All codes you requested have been changed.

2023-01-23 21:57 UTC, mmzeynalli requested changes

2023-01-23 21:57 UTC, mmzeynalli commented on cargo_backend/accounts/models.py
> +        extra_fields.setdefault('birth_date', timezone.now)
should not it be `timezone.now()`?

2023-01-23 21:57 UTC, mmzeynalli commented on cargo_backend/accounts/tests/user_factory.py
> +    phone = generate_phone_and_fin()
oh, you do not need this. Just add fields that are almost always required. If you remove phone, gender from factory, you can still create object like `UserModelFactory(email=x, gender='male', phone='xxx')`

2023-01-24 09:37 UTC, mmzeynalli approved these changes

2023-01-24 09:37 UTC, merged