core models and its tests added
anarbyrm/cargo-api pull request #4
Opened 2023-01-25 10:51 UTC by anarbyrm

2023-01-25 19:18 UTC, mmzeynalli requested changes

2023-01-25 19:18 UTC, mmzeynalli commented on cargo_backend/core/models.py
> +    date_published = models.DateTimeField(auto_now_add=True)
Try to stick created_at, updated_at fields. No need to modify them to different names

2023-01-25 19:18 UTC, mmzeynalli commented on requirements.txt
> +
pillow?

2023-01-25 19:18 UTC, mmzeynalli commented
It would also be better to have file structure list this

tests/
  - factories/
     - core
     - account
   tests.py

2023-01-25 19:31 UTC, anarbyrm commented on requirements.txt
> +
for image field in news model

2023-01-25 19:34 UTC, anarbyrm commented on cargo_backend/core/models.py
> +    date_published = models.DateTimeField(auto_now_add=True)
do you want to say that only created_at field is enough?

2023-01-25 19:37 UTC, mmzeynalli commented on cargo_backend/core/models.py
> +    date_published = models.DateTimeField(auto_now_add=True)
Instead of date_pblished -> created_at, date_edited -> updated_at

2023-01-25 19:45 UTC, anarbyrm commented on cargo_backend/core/models.py
> +    date_published = models.DateTimeField(auto_now_add=True)
roger

2023-01-30 11:38 UTC, mmzeynalli approved these changes

2023-01-30 11:38 UTC, merged